#!/bin/bash
# Blocks edits to generated files that should not be modified manually.
# These files are produced by the codegen toolchain and will be overwritten
# on the next generation run. To change them, modify the source inputs instead.
#
# Toolchain:
#   tfplugingen-openapi   → provider-code-spec.json
#   tfplugingen-framework → internal/provider/resource_*/*_resource_gen.go
#   tfplugindocs          → docs/**/*.md

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

deny() {
  jq -n --arg reason "$1" '{
    "hookSpecificOutput": {
      "hookEventName": "PreToolUse",
      "permissionDecision": "deny",
      "permissionDecisionReason": $reason
    }
  }'
  exit 0
}

case "$FILE_PATH" in
  # Schema spec generated by tfplugingen-openapi from generator_config.yml
  *provider-code-spec.json)
    deny "Generated file — do not edit. Modify generator_config.yml or the OpenAPI spec, then run tfplugingen-openapi."
    ;;

  # Go resource code generated by tfplugingen-framework from provider-code-spec.json
  *_resource_gen.go)
    deny "Generated file — do not edit. Modify generator_config.yml or the OpenAPI spec, then regenerate."
    ;;

  # Documentation generated by tfplugindocs from resource schemas + examples/
  */docs/*.md)
    deny "Generated file — do not edit. Update the resource schema or files in examples/, then run 'go generate ./...'."
    ;;
esac

exit 0