provider:
  name: panther
resources:
  httpsource:
    create:
      path: /log-sources/http
      method: POST
    read:
      path: /log-sources/http/{id}
      method: GET
    update:
      path: /log-sources/http/{id}
      method: PUT
    delete:
      path: /log-sources/http/{id}
      method: DELETE
    schema:
      ignores:
        - integrationId
  pubsubsource:
    create:
      path: /log-sources/pubsub
      method: POST
    read:
      path: /log-sources/pubsub/{id}
      method: GET
    update:
      path: /log-sources/pubsub/{id}
      method: PUT
    delete:
      path: /log-sources/pubsub/{id}
      method: DELETE
    schema:
      ignores:
        - integrationId
  gcssource:
    create:
      path: /log-sources/gcs
      method: POST
    read:
      path: /log-sources/gcs/{id}
      method: GET
    update:
      path: /log-sources/gcs/{id}
      method: PUT
    delete:
      path: /log-sources/gcs/{id}
      method: DELETE
    schema:
      ignores:
        - integrationId
