# The audit role must be deployed in your AWS account before this resource is
# created. Use the CloudFormation template generated by Panther (UI: Configure
# > Cloud Accounts > Connect a new account) to provision the role, then pass
# its ARN as the audit_role variable.
#
# Caveat: the REST API hardcodes a 24-hour scan interval (1440 minutes) on
# every create/update. Custom intervals set out-of-band (UI or GraphQL) will
# be silently reset on the first `terraform apply` after import.
resource "panther_aws_cloud_account" "example" {
  integration_label = var.integration_label
  aws_account_id    = var.aws_account_id

  aws_scan_config = {
    audit_role = var.audit_role
  }

  region_ignore_list         = var.region_ignore_list
  resource_type_ignore_list  = var.resource_type_ignore_list
  resource_regex_ignore_list = var.resource_regex_ignore_list
}
