// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_gcssource

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func GcssourceResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"credentials": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The GCP credentials JSON content (service account key or WIF config). Required on create, optional on update.",
				MarkdownDescription: "The GCP credentials JSON content (service account key or WIF config). Required on create, optional on update.",
			},
			"credentials_type": schema.StringAttribute{
				Required:            true,
				Description:         "The type of credentials being used: service_account or wif (Workload Identity Federation).",
				MarkdownDescription: "The type of credentials being used: service_account or wif (Workload Identity Federation).",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"service_account",
						"wif",
					),
				},
			},
			"gcs_bucket": schema.StringAttribute{
				Required:            true,
				Description:         "The GCS bucket name",
				MarkdownDescription: "The GCS bucket name",
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "ID of the GCS source to fetch",
				MarkdownDescription: "ID of the GCS source to fetch",
			},
			"integration_label": schema.StringAttribute{
				Required:            true,
				Description:         "The integration label (name)",
				MarkdownDescription: "The integration label (name)",
			},
			"log_stream_type": schema.StringAttribute{
				Required:            true,
				Description:         "The log stream type. Supported log stream types: Auto, JSON, JsonArray, Lines, XML",
				MarkdownDescription: "The log stream type. Supported log stream types: Auto, JSON, JsonArray, Lines, XML",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"Auto",
						"JSON",
						"JsonArray",
						"Lines",
						"XML",
					),
				},
			},
			"log_stream_type_options": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"json_array_envelope_field": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Path to the array value to extract elements from, only applicable if logStreamType is JsonArray. Leave empty if the input JSON is an array itself",
						MarkdownDescription: "Path to the array value to extract elements from, only applicable if logStreamType is JsonArray. Leave empty if the input JSON is an array itself",
					},
					"xml_root_element": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The root element name for XML streams, only applicable if logStreamType is XML. Leave empty if the XML events are not enclosed in a root element",
						MarkdownDescription: "The root element name for XML streams, only applicable if logStreamType is XML. Leave empty if the XML events are not enclosed in a root element",
					},
				},
				CustomType: LogStreamTypeOptionsType{
					ObjectType: types.ObjectType{
						AttrTypes: LogStreamTypeOptionsValue{}.AttributeTypes(ctx),
					},
				},
				Optional: true,
				Computed: true,
			},
			"prefix_log_types": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"excluded_prefixes": schema.ListAttribute{
							ElementType:         types.StringType,
							Optional:            true,
							Computed:            true,
							Description:         "Prefixes to exclude from matching. Supports '*' as a wildcard for dynamic path segments.",
							MarkdownDescription: "Prefixes to exclude from matching. Supports '*' as a wildcard for dynamic path segments.",
						},
						"log_types": schema.ListAttribute{
							ElementType:         types.StringType,
							Optional:            true,
							Computed:            true,
							Description:         "The log types (schemas) to apply for this prefix",
							MarkdownDescription: "The log types (schemas) to apply for this prefix",
						},
						"prefix": schema.StringAttribute{
							Optional:            true,
							Computed:            true,
							Description:         "GCS prefix to match. Leave empty to match all files in the bucket.",
							MarkdownDescription: "GCS prefix to match. Leave empty to match all files in the bucket.",
						},
					},
					CustomType: PrefixLogTypesType{
						ObjectType: types.ObjectType{
							AttrTypes: PrefixLogTypesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Required:            true,
				Description:         "Prefix-based log type mappings for parsing ingested data",
				MarkdownDescription: "Prefix-based log type mappings for parsing ingested data",
			},
			"project_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The GCP project ID. Optional for service_account credentials. Required for WIF.",
				MarkdownDescription: "The GCP project ID. Optional for service_account credentials. Required for WIF.",
			},
			"subscription_id": schema.StringAttribute{
				Required:            true,
				Description:         "The GCP Pub/Sub subscription ID used to receive GCS bucket notifications",
				MarkdownDescription: "The GCP Pub/Sub subscription ID used to receive GCS bucket notifications",
			},
		},
	}
}

type GcssourceModel struct {
	Credentials          types.String              `tfsdk:"credentials"`
	CredentialsType      types.String              `tfsdk:"credentials_type"`
	GcsBucket            types.String              `tfsdk:"gcs_bucket"`
	Id                   types.String              `tfsdk:"id"`
	IntegrationLabel     types.String              `tfsdk:"integration_label"`
	LogStreamType        types.String              `tfsdk:"log_stream_type"`
	LogStreamTypeOptions LogStreamTypeOptionsValue `tfsdk:"log_stream_type_options"`
	PrefixLogTypes       types.List                `tfsdk:"prefix_log_types"`
	ProjectId            types.String              `tfsdk:"project_id"`
	SubscriptionId       types.String              `tfsdk:"subscription_id"`
}

var _ basetypes.ObjectTypable = LogStreamTypeOptionsType{}

type LogStreamTypeOptionsType struct {
	basetypes.ObjectType
}

func (t LogStreamTypeOptionsType) Equal(o attr.Type) bool {
	other, ok := o.(LogStreamTypeOptionsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t LogStreamTypeOptionsType) String() string {
	return "LogStreamTypeOptionsType"
}

func (t LogStreamTypeOptionsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	jsonArrayEnvelopeFieldAttribute, ok := attributes["json_array_envelope_field"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`json_array_envelope_field is missing from object`)

		return nil, diags
	}

	jsonArrayEnvelopeFieldVal, ok := jsonArrayEnvelopeFieldAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`json_array_envelope_field expected to be basetypes.StringValue, was: %T`, jsonArrayEnvelopeFieldAttribute))
	}

	xmlRootElementAttribute, ok := attributes["xml_root_element"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`xml_root_element is missing from object`)

		return nil, diags
	}

	xmlRootElementVal, ok := xmlRootElementAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`xml_root_element expected to be basetypes.StringValue, was: %T`, xmlRootElementAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return LogStreamTypeOptionsValue{
		JsonArrayEnvelopeField: jsonArrayEnvelopeFieldVal,
		XmlRootElement:         xmlRootElementVal,
		state:                  attr.ValueStateKnown,
	}, diags
}

func NewLogStreamTypeOptionsValueNull() LogStreamTypeOptionsValue {
	return LogStreamTypeOptionsValue{
		state: attr.ValueStateNull,
	}
}

func NewLogStreamTypeOptionsValueUnknown() LogStreamTypeOptionsValue {
	return LogStreamTypeOptionsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewLogStreamTypeOptionsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (LogStreamTypeOptionsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing LogStreamTypeOptionsValue Attribute Value",
				"While creating a LogStreamTypeOptionsValue value, a missing attribute value was detected. "+
					"A LogStreamTypeOptionsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LogStreamTypeOptionsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid LogStreamTypeOptionsValue Attribute Type",
				"While creating a LogStreamTypeOptionsValue value, an invalid attribute value was detected. "+
					"A LogStreamTypeOptionsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LogStreamTypeOptionsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("LogStreamTypeOptionsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra LogStreamTypeOptionsValue Attribute Value",
				"While creating a LogStreamTypeOptionsValue value, an extra attribute value was detected. "+
					"A LogStreamTypeOptionsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra LogStreamTypeOptionsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewLogStreamTypeOptionsValueUnknown(), diags
	}

	jsonArrayEnvelopeFieldAttribute, ok := attributes["json_array_envelope_field"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`json_array_envelope_field is missing from object`)

		return NewLogStreamTypeOptionsValueUnknown(), diags
	}

	jsonArrayEnvelopeFieldVal, ok := jsonArrayEnvelopeFieldAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`json_array_envelope_field expected to be basetypes.StringValue, was: %T`, jsonArrayEnvelopeFieldAttribute))
	}

	xmlRootElementAttribute, ok := attributes["xml_root_element"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`xml_root_element is missing from object`)

		return NewLogStreamTypeOptionsValueUnknown(), diags
	}

	xmlRootElementVal, ok := xmlRootElementAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`xml_root_element expected to be basetypes.StringValue, was: %T`, xmlRootElementAttribute))
	}

	if diags.HasError() {
		return NewLogStreamTypeOptionsValueUnknown(), diags
	}

	return LogStreamTypeOptionsValue{
		JsonArrayEnvelopeField: jsonArrayEnvelopeFieldVal,
		XmlRootElement:         xmlRootElementVal,
		state:                  attr.ValueStateKnown,
	}, diags
}

func NewLogStreamTypeOptionsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) LogStreamTypeOptionsValue {
	object, diags := NewLogStreamTypeOptionsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewLogStreamTypeOptionsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t LogStreamTypeOptionsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewLogStreamTypeOptionsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewLogStreamTypeOptionsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewLogStreamTypeOptionsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewLogStreamTypeOptionsValueMust(LogStreamTypeOptionsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t LogStreamTypeOptionsType) ValueType(ctx context.Context) attr.Value {
	return LogStreamTypeOptionsValue{}
}

var _ basetypes.ObjectValuable = LogStreamTypeOptionsValue{}

type LogStreamTypeOptionsValue struct {
	JsonArrayEnvelopeField basetypes.StringValue `tfsdk:"json_array_envelope_field"`
	XmlRootElement         basetypes.StringValue `tfsdk:"xml_root_element"`
	state                  attr.ValueState
}

func (v LogStreamTypeOptionsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["json_array_envelope_field"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["xml_root_element"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.JsonArrayEnvelopeField.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["json_array_envelope_field"] = val

		val, err = v.XmlRootElement.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["xml_root_element"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v LogStreamTypeOptionsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v LogStreamTypeOptionsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v LogStreamTypeOptionsValue) String() string {
	return "LogStreamTypeOptionsValue"
}

func (v LogStreamTypeOptionsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"json_array_envelope_field": basetypes.StringType{},
		"xml_root_element":          basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"json_array_envelope_field": v.JsonArrayEnvelopeField,
			"xml_root_element":          v.XmlRootElement,
		})

	return objVal, diags
}

func (v LogStreamTypeOptionsValue) Equal(o attr.Value) bool {
	other, ok := o.(LogStreamTypeOptionsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.JsonArrayEnvelopeField.Equal(other.JsonArrayEnvelopeField) {
		return false
	}

	if !v.XmlRootElement.Equal(other.XmlRootElement) {
		return false
	}

	return true
}

func (v LogStreamTypeOptionsValue) Type(ctx context.Context) attr.Type {
	return LogStreamTypeOptionsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v LogStreamTypeOptionsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"json_array_envelope_field": basetypes.StringType{},
		"xml_root_element":          basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = PrefixLogTypesType{}

type PrefixLogTypesType struct {
	basetypes.ObjectType
}

func (t PrefixLogTypesType) Equal(o attr.Type) bool {
	other, ok := o.(PrefixLogTypesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t PrefixLogTypesType) String() string {
	return "PrefixLogTypesType"
}

func (t PrefixLogTypesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	excludedPrefixesAttribute, ok := attributes["excluded_prefixes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`excluded_prefixes is missing from object`)

		return nil, diags
	}

	excludedPrefixesVal, ok := excludedPrefixesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`excluded_prefixes expected to be basetypes.ListValue, was: %T`, excludedPrefixesAttribute))
	}

	logTypesAttribute, ok := attributes["log_types"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`log_types is missing from object`)

		return nil, diags
	}

	logTypesVal, ok := logTypesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`log_types expected to be basetypes.ListValue, was: %T`, logTypesAttribute))
	}

	prefixAttribute, ok := attributes["prefix"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`prefix is missing from object`)

		return nil, diags
	}

	prefixVal, ok := prefixAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`prefix expected to be basetypes.StringValue, was: %T`, prefixAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return PrefixLogTypesValue{
		ExcludedPrefixes: excludedPrefixesVal,
		LogTypes:         logTypesVal,
		Prefix:           prefixVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewPrefixLogTypesValueNull() PrefixLogTypesValue {
	return PrefixLogTypesValue{
		state: attr.ValueStateNull,
	}
}

func NewPrefixLogTypesValueUnknown() PrefixLogTypesValue {
	return PrefixLogTypesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewPrefixLogTypesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (PrefixLogTypesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing PrefixLogTypesValue Attribute Value",
				"While creating a PrefixLogTypesValue value, a missing attribute value was detected. "+
					"A PrefixLogTypesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PrefixLogTypesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid PrefixLogTypesValue Attribute Type",
				"While creating a PrefixLogTypesValue value, an invalid attribute value was detected. "+
					"A PrefixLogTypesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PrefixLogTypesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("PrefixLogTypesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra PrefixLogTypesValue Attribute Value",
				"While creating a PrefixLogTypesValue value, an extra attribute value was detected. "+
					"A PrefixLogTypesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra PrefixLogTypesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewPrefixLogTypesValueUnknown(), diags
	}

	excludedPrefixesAttribute, ok := attributes["excluded_prefixes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`excluded_prefixes is missing from object`)

		return NewPrefixLogTypesValueUnknown(), diags
	}

	excludedPrefixesVal, ok := excludedPrefixesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`excluded_prefixes expected to be basetypes.ListValue, was: %T`, excludedPrefixesAttribute))
	}

	logTypesAttribute, ok := attributes["log_types"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`log_types is missing from object`)

		return NewPrefixLogTypesValueUnknown(), diags
	}

	logTypesVal, ok := logTypesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`log_types expected to be basetypes.ListValue, was: %T`, logTypesAttribute))
	}

	prefixAttribute, ok := attributes["prefix"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`prefix is missing from object`)

		return NewPrefixLogTypesValueUnknown(), diags
	}

	prefixVal, ok := prefixAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`prefix expected to be basetypes.StringValue, was: %T`, prefixAttribute))
	}

	if diags.HasError() {
		return NewPrefixLogTypesValueUnknown(), diags
	}

	return PrefixLogTypesValue{
		ExcludedPrefixes: excludedPrefixesVal,
		LogTypes:         logTypesVal,
		Prefix:           prefixVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewPrefixLogTypesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) PrefixLogTypesValue {
	object, diags := NewPrefixLogTypesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewPrefixLogTypesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t PrefixLogTypesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewPrefixLogTypesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewPrefixLogTypesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewPrefixLogTypesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewPrefixLogTypesValueMust(PrefixLogTypesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t PrefixLogTypesType) ValueType(ctx context.Context) attr.Value {
	return PrefixLogTypesValue{}
}

var _ basetypes.ObjectValuable = PrefixLogTypesValue{}

type PrefixLogTypesValue struct {
	ExcludedPrefixes basetypes.ListValue   `tfsdk:"excluded_prefixes"`
	LogTypes         basetypes.ListValue   `tfsdk:"log_types"`
	Prefix           basetypes.StringValue `tfsdk:"prefix"`
	state            attr.ValueState
}

func (v PrefixLogTypesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["excluded_prefixes"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["log_types"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["prefix"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.ExcludedPrefixes.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["excluded_prefixes"] = val

		val, err = v.LogTypes.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["log_types"] = val

		val, err = v.Prefix.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["prefix"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v PrefixLogTypesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v PrefixLogTypesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v PrefixLogTypesValue) String() string {
	return "PrefixLogTypesValue"
}

func (v PrefixLogTypesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var excludedPrefixesVal basetypes.ListValue
	switch {
	case v.ExcludedPrefixes.IsUnknown():
		excludedPrefixesVal = types.ListUnknown(types.StringType)
	case v.ExcludedPrefixes.IsNull():
		excludedPrefixesVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		excludedPrefixesVal, d = types.ListValue(types.StringType, v.ExcludedPrefixes.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"excluded_prefixes": basetypes.ListType{
				ElemType: types.StringType,
			},
			"log_types": basetypes.ListType{
				ElemType: types.StringType,
			},
			"prefix": basetypes.StringType{},
		}), diags
	}

	var logTypesVal basetypes.ListValue
	switch {
	case v.LogTypes.IsUnknown():
		logTypesVal = types.ListUnknown(types.StringType)
	case v.LogTypes.IsNull():
		logTypesVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		logTypesVal, d = types.ListValue(types.StringType, v.LogTypes.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"excluded_prefixes": basetypes.ListType{
				ElemType: types.StringType,
			},
			"log_types": basetypes.ListType{
				ElemType: types.StringType,
			},
			"prefix": basetypes.StringType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"excluded_prefixes": basetypes.ListType{
			ElemType: types.StringType,
		},
		"log_types": basetypes.ListType{
			ElemType: types.StringType,
		},
		"prefix": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"excluded_prefixes": excludedPrefixesVal,
			"log_types":         logTypesVal,
			"prefix":            v.Prefix,
		})

	return objVal, diags
}

func (v PrefixLogTypesValue) Equal(o attr.Value) bool {
	other, ok := o.(PrefixLogTypesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ExcludedPrefixes.Equal(other.ExcludedPrefixes) {
		return false
	}

	if !v.LogTypes.Equal(other.LogTypes) {
		return false
	}

	if !v.Prefix.Equal(other.Prefix) {
		return false
	}

	return true
}

func (v PrefixLogTypesValue) Type(ctx context.Context) attr.Type {
	return PrefixLogTypesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v PrefixLogTypesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"excluded_prefixes": basetypes.ListType{
			ElemType: types.StringType,
		},
		"log_types": basetypes.ListType{
			ElemType: types.StringType,
		},
		"prefix": basetypes.StringType{},
	}
}
