# Manage an AWS Cloud Account integration for Panther's compliance scanner.
# The audit role must be deployed in your AWS account before this resource is
# created. Use the CloudFormation template generated by Panther (UI: Configure
# > Cloud Accounts > Connect a new account) to provision the role, then pass
# its ARN here.
resource "panther_aws_cloud_account" "example" {
  integration_label = "production-aws"
  aws_account_id    = "123456789012"

  aws_scan_config = {
    audit_role = "arn:aws:iam::123456789012:role/PantherAuditRole"
  }

  region_ignore_list         = []
  resource_type_ignore_list  = []
  resource_regex_ignore_list = []
}
