# Manage an AWS Cloud Account integration for Panther's compliance scanner.
# The audit role must be deployed in your AWS account before this resource is
# created. Use the CloudFormation template generated by Panther (UI: Configure
# > Cloud Accounts > Connect a new account) to provision the role, then pass
# its ARN here.
#
# Caveat — scan interval: this resource does not expose `scanIntervalMins`.
# The REST API hardcodes a 24-hour scan interval (1440 minutes) on every
# create/update. If you previously customized the scan interval out-of-band
# (Panther UI or GraphQL), `terraform apply` will silently reset it back to
# 1440 on the next apply.
resource "panther_aws_cloud_account" "example" {
  integration_label = "production-aws"
  aws_account_id    = "123456789012"

  aws_scan_config = {
    audit_role = "arn:aws:iam::123456789012:role/PantherAuditRole"
  }

  region_ignore_list         = []
  resource_type_ignore_list  = []
  resource_regex_ignore_list = []
}
