// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_aws_cloud_account

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func AwsCloudAccountResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"aws_account_id": schema.StringAttribute{
				Required:            true,
				Description:         "The 12-digit AWS account ID",
				MarkdownDescription: "The 12-digit AWS account ID",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^[0-9]{12}$"), ""),
				},
			},
			"aws_scan_config": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"audit_role": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The IAM role ARN that Panther assumes to scan the AWS account",
						MarkdownDescription: "The IAM role ARN that Panther assumes to scan the AWS account",
					},
				},
				CustomType: AwsScanConfigType{
					ObjectType: types.ObjectType{
						AttrTypes: AwsScanConfigValue{}.AttributeTypes(ctx),
					},
				},
				Required: true,
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "ID of the AWS Cloud Account to fetch",
				MarkdownDescription: "ID of the AWS Cloud Account to fetch",
			},
			"integration_label": schema.StringAttribute{
				Required:            true,
				Description:         "The display name for the AWS Cloud Account integration",
				MarkdownDescription: "The display name for the AWS Cloud Account integration",
				Validators: []validator.String{
					stringvalidator.LengthAtMost(36),
					stringvalidator.RegexMatches(regexp.MustCompile("^[0-9a-zA-Z- ]+$"), ""),
				},
			},
			"region_ignore_list": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Regions to exclude from scanning",
				MarkdownDescription: "Regions to exclude from scanning",
			},
			"resource_regex_ignore_list": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Regex patterns matching resource ARNs to exclude from scanning",
				MarkdownDescription: "Regex patterns matching resource ARNs to exclude from scanning",
			},
			"resource_type_ignore_list": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Resource types to exclude from scanning (e.g. AWS.S3.Bucket)",
				MarkdownDescription: "Resource types to exclude from scanning (e.g. AWS.S3.Bucket)",
			},
		},
	}
}

type AwsCloudAccountModel struct {
	AwsAccountId            types.String       `tfsdk:"aws_account_id"`
	AwsScanConfig           AwsScanConfigValue `tfsdk:"aws_scan_config"`
	Id                      types.String       `tfsdk:"id"`
	IntegrationLabel        types.String       `tfsdk:"integration_label"`
	RegionIgnoreList        types.List         `tfsdk:"region_ignore_list"`
	ResourceRegexIgnoreList types.List         `tfsdk:"resource_regex_ignore_list"`
	ResourceTypeIgnoreList  types.List         `tfsdk:"resource_type_ignore_list"`
}

var _ basetypes.ObjectTypable = AwsScanConfigType{}

type AwsScanConfigType struct {
	basetypes.ObjectType
}

func (t AwsScanConfigType) Equal(o attr.Type) bool {
	other, ok := o.(AwsScanConfigType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AwsScanConfigType) String() string {
	return "AwsScanConfigType"
}

func (t AwsScanConfigType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	auditRoleAttribute, ok := attributes["audit_role"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`audit_role is missing from object`)

		return nil, diags
	}

	auditRoleVal, ok := auditRoleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`audit_role expected to be basetypes.StringValue, was: %T`, auditRoleAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AwsScanConfigValue{
		AuditRole: auditRoleVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewAwsScanConfigValueNull() AwsScanConfigValue {
	return AwsScanConfigValue{
		state: attr.ValueStateNull,
	}
}

func NewAwsScanConfigValueUnknown() AwsScanConfigValue {
	return AwsScanConfigValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAwsScanConfigValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AwsScanConfigValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AwsScanConfigValue Attribute Value",
				"While creating a AwsScanConfigValue value, a missing attribute value was detected. "+
					"A AwsScanConfigValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AwsScanConfigValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AwsScanConfigValue Attribute Type",
				"While creating a AwsScanConfigValue value, an invalid attribute value was detected. "+
					"A AwsScanConfigValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AwsScanConfigValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AwsScanConfigValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AwsScanConfigValue Attribute Value",
				"While creating a AwsScanConfigValue value, an extra attribute value was detected. "+
					"A AwsScanConfigValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AwsScanConfigValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAwsScanConfigValueUnknown(), diags
	}

	auditRoleAttribute, ok := attributes["audit_role"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`audit_role is missing from object`)

		return NewAwsScanConfigValueUnknown(), diags
	}

	auditRoleVal, ok := auditRoleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`audit_role expected to be basetypes.StringValue, was: %T`, auditRoleAttribute))
	}

	if diags.HasError() {
		return NewAwsScanConfigValueUnknown(), diags
	}

	return AwsScanConfigValue{
		AuditRole: auditRoleVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewAwsScanConfigValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AwsScanConfigValue {
	object, diags := NewAwsScanConfigValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAwsScanConfigValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AwsScanConfigType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAwsScanConfigValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAwsScanConfigValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAwsScanConfigValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAwsScanConfigValueMust(AwsScanConfigValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AwsScanConfigType) ValueType(ctx context.Context) attr.Value {
	return AwsScanConfigValue{}
}

var _ basetypes.ObjectValuable = AwsScanConfigValue{}

type AwsScanConfigValue struct {
	AuditRole basetypes.StringValue `tfsdk:"audit_role"`
	state     attr.ValueState
}

func (v AwsScanConfigValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["audit_role"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.AuditRole.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["audit_role"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AwsScanConfigValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AwsScanConfigValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AwsScanConfigValue) String() string {
	return "AwsScanConfigValue"
}

func (v AwsScanConfigValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"audit_role": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"audit_role": v.AuditRole,
		})

	return objVal, diags
}

func (v AwsScanConfigValue) Equal(o attr.Value) bool {
	other, ok := o.(AwsScanConfigValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AuditRole.Equal(other.AuditRole) {
		return false
	}

	return true
}

func (v AwsScanConfigValue) Type(ctx context.Context) attr.Type {
	return AwsScanConfigType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AwsScanConfigValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"audit_role": basetypes.StringType{},
	}
}
