// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_log_source_alarm

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func LogSourceAlarmResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"minutes_threshold": schema.Int64Attribute{
				Required:            true,
				Description:         "The no-data evaluation period in minutes. Minimum 15, maximum 43200 (30 days).",
				MarkdownDescription: "The no-data evaluation period in minutes. Minimum 15, maximum 43200 (30 days).",
			},
			"source_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The ID of the log source",
				MarkdownDescription: "The ID of the log source",
			},
			"type": schema.StringAttribute{
				Computed:            true,
				Description:         "The alarm type",
				MarkdownDescription: "The alarm type",
			},
		},
	}
}

type LogSourceAlarmModel struct {
	MinutesThreshold types.Int64  `tfsdk:"minutes_threshold"`
	SourceId         types.String `tfsdk:"source_id"`
	Type             types.String `tfsdk:"type"`
}
